insert into products (name, description, price, quantity) values ('Teclado mecánico VGS', 'Teclado mecánico de la marca VSG tamaño 100%', 2000000.0, 110);
insert into products (name, description, price, quantity) values ('Ratón óptico Logitech', 'Ratón óptico inalámbrico Logitech con sensor de alta precisión', 150000.0, 200);
insert into products (name, description, price, quantity) values ('Monitor Samsung 27"', 'Monitor Samsung 27" Full HD con tecnología Flicker Free', 800000.0, 50);
insert into products (name, description, price, quantity) values ('Auriculares Sony WH-1000XM4', 'Auriculares inalámbricos con cancelación de ruido de la marca Sony', 1200000.0, 30);
insert into products (name, description, price, quantity) values ('Laptop Dell Inspiron', 'Laptop Dell Inspiron con procesador Intel i7 y 16GB de RAM', 3500000.0, 15);
insert into products (name, description, price, quantity) values ('Smartphone Samsung Galaxy S21', 'Smartphone Samsung Galaxy S21 con pantalla AMOLED y 128GB de almacenamiento', 2500000.0, 60);
insert into products (name, description, price, quantity) values ('Tablet Apple iPad Air', 'Tablet Apple iPad Air con pantalla Retina y chip A14 Bionic', 2800000.0, 40);
insert into products (name, description, price, quantity) values ('Impresora HP LaserJet', 'Impresora láser multifuncional HP LaserJet Pro', 450000.0, 25);
insert into products (name, description, price, quantity) values ('Cámara Canon EOS 2000D', 'Cámara réflex digital Canon EOS 2000D con lente EF-S 18-55mm', 2200000.0, 18);
insert into products (name, description, price, quantity) values ('Smartwatch Apple Watch Series 6', 'Smartwatch Apple Watch Series 6 con GPS y monitor de oxígeno en sangre', 1800000.0, 35);
insert into products (name, description, price, quantity) values ('Disco Duro Externo Seagate', 'Disco duro externo Seagate de 2TB con conexión USB 3.0', 320000.0, 70);
insert into products (name, description, price, quantity) values ('Consola Nintendo Switch', 'Consola de videojuegos Nintendo Switch con controles Joy-Con', 1300000.0, 22);
insert into products (name, description, price, quantity) values ('TV LG OLED 55"', 'Televisor LG OLED de 55" con resolución 4K y HDR', 6000000.0, 10);
insert into products (name, description, price, quantity) values ('Router TP-Link AC1750', 'Router inalámbrico TP-Link AC1750 con doble banda y alta velocidad', 250000.0, 50);
insert into products (name, description, price, quantity) values ('Altavoces Bose SoundLink', 'Altavoces Bluetooth Bose SoundLink con sonido envolvente', 700000.0, 40);
insert into products (name, description, price, quantity) values ('Smartwatch Fitbit Charge 4', 'Smartwatch Fitbit Charge 4 con GPS y monitoreo de actividad', 400000.0, 60);
insert into products (name, description, price, quantity) values ('Proyector Epson Home Cinema', 'Proyector Epson Home Cinema con resolución Full HD y 3000 lúmenes', 2500000.0, 12);
insert into products (name, description, price, quantity) values ('Teclado Logitech K120', 'Teclado con cable Logitech K120 resistente a salpicaduras', 80000.0, 150);
insert into products (name, description, price, quantity) values ('Silla de oficina Ergohuman', 'Silla de oficina ergonómica Ergohuman con soporte lumbar ajustable', 1200000.0, 20);
insert into products (name, description, price, quantity) values ('Micrófono Blue Yeti', 'Micrófono USB Blue Yeti con patrón de grabación múltiple', 600000.0, 25);
insert into products (name, description, price, quantity) values ('Disco SSD Samsung 970 EVO', 'Disco SSD Samsung 970 EVO NVMe de 1TB con velocidad de lectura de 3500MB/s', 500000.0, 50);
insert into products (name, description, price, quantity) values ('Mochila Targus para Laptop', 'Mochila Targus para laptop de hasta 15.6" con múltiples compartimentos', 120000.0, 70);
insert into products (name, description, price, quantity) values ('Cámara GoPro HERO9', 'Cámara de acción GoPro HERO9 con estabilización de imagen y 5K', 1800000.0, 15);
insert into products (name, description, price, quantity) values ('Monitor LG UltraWide', 'Monitor LG UltraWide de 34" con resolución WQHD y HDR10', 2200000.0, 18);
insert into products (name, description, price, quantity) values ('Memoria USB Kingston 64GB', 'Memoria USB Kingston DataTraveler de 64GB con USB 3.1', 40000.0, 120);
insert into products (name, description, price, quantity) values ('Ventilador Dyson Air Multiplier', 'Ventilador sin aspas Dyson Air Multiplier con control remoto', 1800000.0, 12);
insert into products (name, description, price, quantity) values ('Impresora Canon Pixma', 'Impresora multifuncional Canon Pixma con impresión inalámbrica', 350000.0, 30);
insert into products (name, description, price, quantity) values ('Auriculares JBL Tune 500BT', 'Auriculares inalámbricos JBL Tune 500BT con sonido puro y claro', 150000.0, 40);
insert into products (name, description, price, quantity) values ('Smartphone OnePlus 9', 'Smartphone OnePlus 9 con pantalla Fluid AMOLED y 128GB de almacenamiento', 2200000.0, 45);
insert into products (name, description, price, quantity) values ('Reloj Garmin Forerunner 245', 'Reloj deportivo Garmin Forerunner 245 con GPS y métricas avanzadas de carrera', 800000.0, 25);
insert into products (name, description, price, quantity) values ('Proyector BenQ HT2050A', 'Proyector BenQ HT2050A con resolución Full HD y 2200 lúmenes', 2700000.0, 10);
insert into products (name, description, price, quantity) values ('Smart TV Sony Bravia 65"', 'Televisor inteligente Sony Bravia de 65" con resolución 4K y Android TV', 5500000.0, 12);
insert into products (name, description, price, quantity) values ('Tablet Samsung Galaxy Tab S7', 'Tablet Samsung Galaxy Tab S7 con pantalla de 11" y S Pen incluido', 2000000.0, 30);
insert into products (name, description, price, quantity) values ('Altavoz Amazon Echo', 'Altavoz inteligente Amazon Echo con Alexa y control por voz', 300000.0, 45);
insert into products (name, description, price, quantity) values ('Ratón Razer DeathAdder', 'Ratón para juegos Razer DeathAdder con sensor óptico de alta precisión', 180000.0, 50);
insert into products (name, description, price, quantity) values ('Teclado Corsair K95', 'Teclado mecánico Corsair K95 RGB con switches Cherry MX', 700000.0, 22);
insert into products (name, description, price, quantity) values ('Silla gaming DXRacer', 'Silla gaming DXRacer con diseño ergonómico y reclinable', 900000.0, 15);
insert into products (name, description, price, quantity) values ('Router Asus RT-AX88U', 'Router inalámbrico Asus RT-AX88U con tecnología Wi-Fi 6', 1500000.0, 20);
insert into products (name, description, price, quantity) values ('Cámara Nikon D3500', 'Cámara réflex digital Nikon D3500 con lente AF-P DX 18-55mm', 1800000.0, 18);
insert into products (name, description, price, quantity) values ('Micrófono Shure SM7B', 'Micrófono dinámico Shure SM7B con calidad de estudio', 1500000.0, 10);
insert into products (name, description, price, quantity) values ('Disco Duro Externo WD My Passport', 'Disco duro externo WD My Passport de 4TB con cifrado por hardware', 500000.0, 35);
insert into products (name, description, price, quantity) values ('TV Samsung QLED 50"', 'Televisor Samsung QLED de 50" con resolución 4K y tecnología Quantum Dot', 3000000.0, 20);
insert into products (name, description, price, quantity) values ('Laptop HP Pavilion Gaming', 'Laptop HP Pavilion Gaming con procesador AMD Ryzen 5 y GTX 1650', 2800000.0, 15);
insert into products (name, description, price, quantity) values ('Auriculares Bose QuietComfort 35', 'Auriculares inalámbricos Bose QuietComfort 35 con cancelación de ruido', 1500000.0, 25);
insert into products (name, description, price, quantity) values ('Disco SSD Crucial MX500', 'Disco SSD Crucial MX500 de 1TB con lectura secuencial de 560MB/s', 400000.0, 50);
insert into products (name, description, price, quantity) values ('Mochila SwissGear para Laptop', 'Mochila SwissGear para laptop de hasta 17" con múltiples compartimentos', 150000.0, 65);
insert into products (name, description, price, quantity) values ('Cámara Sony Alpha a6000', 'Cámara sin espejo Sony Alpha a6000 con lente 16-50mm', 2000000.0, 18);
insert into products (name, description, price, quantity) values ('Monitor Dell Ultrasharp 27"', 'Monitor Dell Ultrasharp de 27" con resolución 4K y color preciso', 3000000.0, 14);
insert into products (name, description, price, quantity) values ('Memoria USB SanDisk Ultra 128GB', 'Memoria USB SanDisk Ultra de 128GB con USB 3.0', 80000.0, 110);
insert into products (name, description, price, quantity) values ('Ventilador de Torre Honeywell', 'Ventilador de torre Honeywell QuietSet con 5 niveles de potencia', 200000.0, 45);
insert into products (name, description, price, quantity) values ('Impresora Epson EcoTank', 'Impresora multifuncional Epson EcoTank con sistema de tinta continua', 800000.0, 20);
insert into products (name, description, price, quantity) values ('Auriculares AKG N60NC', 'Auriculares inalámbricos AKG N60NC con cancelación de ruido', 600000.0, 30);
insert into products (name, description, price, quantity) values ('Smartphone Google Pixel 5', 'Smartphone Google Pixel 5 con pantalla OLED y 128GB de almacenamiento', 2200000.0, 40);
insert into products (name, description, price, quantity) values ('Reloj Suunto 7', 'Reloj inteligente Suunto 7 con GPS y Wear OS', 1000000.0, 20);
insert into products (name, description, price, quantity) values ('Proyector Optoma HD146X', 'Proyector Optoma HD146X con resolución Full HD y 3600 lúmenes', 1800000.0, 15);
insert into products (name, description, price, quantity) values ('Smart TV TCL 43"', 'Televisor inteligente TCL de 43" con resolución 4K y Roku TV', 1400000.0, 25);
insert into products (name, description, price, quantity) values ('Tablet Lenovo Tab M10', 'Tablet Lenovo Tab M10 con pantalla de 10.1" y 32GB de almacenamiento', 600000.0, 35);
insert into products (name, description, price, quantity) values ('Altavoz Sony SRS-XB43', 'Altavoz Bluetooth Sony SRS-XB43 con sonido EXTRA BASS', 800000.0, 30);
insert into products (name, description, price, quantity) values ('Ratón Logitech MX Master 3', 'Ratón inalámbrico Logitech MX Master 3 con desplazamiento electromagnético', 350000.0, 40);
insert into products (name, description, price, quantity) values ('Teclado Razer BlackWidow', 'Teclado mecánico Razer BlackWidow con iluminación RGB', 400000.0, 28);
insert into products (name, description, price, quantity) values ('Silla gaming Secretlab Titan', 'Silla gaming Secretlab Titan con soporte lumbar ajustable', 1500000.0, 12);
insert into products (name, description, price, quantity) values ('Router Netgear Nighthawk AX12', 'Router inalámbrico Netgear Nighthawk AX12 con Wi-Fi 6', 1800000.0, 18);
insert into products (name, description, price, quantity) values ('Cámara Fujifilm X-T30', 'Cámara sin espejo Fujifilm X-T30 con lente XC 15-45mm', 2500000.0, 14);
insert into products (name, description, price, quantity) values ('Micrófono Rode NT1-A', 'Micrófono de condensador Rode NT1-A con bajo nivel de ruido', 1000000.0, 20);
insert into products (name, description, price, quantity) values ('Disco Duro Externo Toshiba Canvio', 'Disco duro externo Toshiba Canvio de 1TB con USB 3.0', 200000.0, 80);
insert into products (name, description, price, quantity) values ('TV Philips Ambilight 55"', 'Televisor Philips Ambilight de 55" con resolución 4K y HDR', 3000000.0, 15);
insert into products (name, description, price, quantity) values ('Laptop Asus ZenBook 14', 'Laptop Asus ZenBook 14 con procesador Intel i5 y 8GB de RAM', 3000000.0, 12);
insert into products (name, description, price, quantity) values ('Auriculares Sennheiser HD 450BT', 'Auriculares inalámbricos Sennheiser HD 450BT con cancelación de ruido', 600000.0, 30);
insert into products (name, description, price, quantity) values ('Disco SSD Western Digital Blue', 'Disco SSD Western Digital Blue de 500GB con lectura de 560MB/s', 300000.0, 45);
insert into products (name, description, price, quantity) values ('Mochila Samsonite para Laptop', 'Mochila Samsonite para laptop de hasta 15.6" con protección acolchada', 100000.0, 60);
insert into products (name, description, price, quantity) values ('Cámara Panasonic Lumix G7', 'Cámara sin espejo Panasonic Lumix G7 con lente 14-42mm', 2000000.0, 18);
insert into products (name, description, price, quantity) values ('Monitor BenQ PD2700Q', 'Monitor BenQ PD2700Q de 27" con resolución QHD y tecnología IPS', 1500000.0, 20);
insert into products (name, description, price, quantity) values ('Memoria USB PNY Turbo 256GB', 'Memoria USB PNY Turbo de 256GB con USB 3.0', 100000.0, 90);
insert into products (name, description, price, quantity) values ('Ventilador Rowenta Turbo Silence', 'Ventilador de pie Rowenta Turbo Silence con 5 velocidades', 300000.0, 35);
insert into products (name, description, price, quantity) values ('Impresora Brother HL-L2350DW', 'Impresora láser Brother HL-L2350DW con impresión dúplex', 400000.0, 25);
insert into products (name, description, price, quantity) values ('Auriculares Audio-Technica ATH-M50X', 'Auriculares de estudio Audio-Technica ATH-M50X con calidad profesional', 500000.0, 30);
insert into products (name, description, price, quantity) values ('Smartphone Xiaomi Mi 11', 'Smartphone Xiaomi Mi 11 con pantalla AMOLED y 128GB de almacenamiento', 2000000.0, 40);
insert into products (name, description, price, quantity) values ('Reloj Polar Vantage V2', 'Reloj deportivo Polar Vantage V2 con GPS y métricas avanzadas', 1500000.0, 20);
insert into products (name, description, price, quantity) values ('Proyector ViewSonic PX701HD', 'Proyector ViewSonic PX701HD con resolución Full HD y 3500 lúmenes', 1500000.0, 18);
insert into products (name, description, price, quantity) values ('Smart TV Hisense 50"', 'Televisor inteligente Hisense de 50" con resolución 4K y Android TV', 1200000.0, 22);
insert into products (name, description, price, quantity) values ('Tablet Amazon Fire HD 10', 'Tablet Amazon Fire HD 10 con pantalla de 10.1" y 64GB de almacenamiento', 400000.0, 35);
insert into products (name, description, price, quantity) values ('Altavoz JBL Flip 5', 'Altavoz Bluetooth JBL Flip 5 con sonido potente y resistente al agua', 300000.0, 40);
